import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
//import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Bharath Gajula Kambaz ",
  description: "Generated by Bharath Web dev app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
          style={{
            display: "flex",
            flexDirection: "column",
            minHeight: "100vh"
          }}>
              <div style={{ flex: 1 }}>
                {children}
              </div>
              <footer style={{ textAlign: "center"}}>
                Created by Bharath Gajula (CS5610) &nbsp;|&nbsp;
                <a href="https://github.com/sai21gajula/kambaz-next-js" target="_blank" rel="noopener noreferrer">
                  GitHub Project
          </a>
        </footer>
      </body>
    </html>
  );
}
